### ISSUE TITLE
Crash after today’s commits

### ISSUE THREAD

**Issue by pacholik** [gruvbox-community/gruvbox#192]
neovim 0.7.2

```
Error detected while processing /home/pacholik/.config/nvim/bundle/gruvbox/colors/gruvbox.vim:
line  843:
W18: Invalid character in group name
line  844:
W18: Invalid character in group name
line  845:
W18: Invalid character in group name
line  846:
W18: Invalid character in group name
line  847:
W18: Invalid character in group name
line  848:
W18: Invalid character in group name
line  850:
W18: Invalid character in group name
line  851:
W18: Invalid character in group name
line  852:
W18: Invalid character in group name
line  854:
W18: Invalid character in group name
line  856:
W18: Invalid character in group name
line  859:
W18: Invalid character in group name
line  860:
W18: Invalid character in group name
line  862:
W18: Invalid character in group name
line  863:
W18: Invalid character in group name
line  864:
W18: Invalid character in group name
line  866:
W18: Invalid character in group name
line  869:
W18: Invalid character in group name
line  871:
W18: Invalid character in group name
line  872:
W18: Invalid character in group name
line  874:
W18: Invalid character in group name
line  875:
W18: Invalid character in group name
line  877:
W18: Invalid character in group name
line  882:
W18: Invalid character in group name
line  883:
W18: Invalid character in group name
line  884:
W18: Invalid character in group name
line  885:
W18: Invalid character in group name
line  886:
W18: Invalid character in group name
line  887:
W18: Invalid character in group name
line  889:
W18: Invalid character in group name
line  892:
W18: Invalid character in group name
line  894:
W18: Invalid character in group name
line  895:
W18: Invalid character in group name
line  896:
W18: Invalid character in group name
line  897:
W18: Invalid character in group name
line  899:
W18: Invalid character in group name
line  900:
W18: Invalid character in group name
line  902:
W18: Invalid character in group name
line  904:
W18: Invalid character in group name
line  906:
W18: Invalid character in group name
line  909:
W18: Invalid character in group name
line  910:
W18: Invalid character in group name
line  911:
W18: Invalid character in group name
line  912:
W18: Invalid character in group name
line  913:
W18: Invalid character in group name
line  914:
W18: Invalid character in group name
line  915:
W18: Invalid character in group name
line  916:
W18: Invalid character in group name
line  917:
W18: Invalid character in group name
line  918:
W18: Invalid character in group name
line  919:
W18: Invalid character in group name
line  920:
W18: Invalid character in group name
line  922:
W18: Invalid character in group name
line  923:
W18: Invalid character in group name
line  924:
W18: Invalid character in group name
line  925:
W18: Invalid character in group name
line  927:
W18: Invalid character in group name
line  928:
W18: Invalid character in group name
line  929:
W18: Invalid character in group name
```

**Comment by rbong** [comment]
Sorry for the crash, what do you get from `echo v:version`?

**Comment by rbong** [comment]
I was looking for a reliable way to check if it was safe to define TreeSitter groups, I think I found it. Let me know if that resolves the issue.

**Comment by seraph** [comment]
@rbong I am still experiencing this with the latest version (commit 121309cebfc5a9b4f71b7b962d0d0df7e82cc456):

```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

Output of `echo v:version` is `800`.

**Comment by rbong** [comment]
Apologies, it should be fixed now. I went digging through Neovim's history to see what version we should check for. There's no kind of dynamic check I can do to make sure the feature is available.

**Comment by thesofakillers** [comment]
I'm still getting this error

```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@iMac-Pro

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.7.2_1/share/nvim"
```

Output of `echo v:version` is `800`


Had to fall back to 2b5b1f777f0583ffb39086d6c16f39e6e37459c0

```
Plug 'gruvbox-community/gruvbox', {'commit':'2b5b1f7'}
```

**Comment by rbong** [comment]
I believe it should now be fixed for you. Apologies.
